# Generated by Django 5.2.6 on 2025-10-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper_trading", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiusagetracker",
            name="requests_limit",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="papertrade",
            name="signal_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
