# Generated by Django 5.2.6 on 2025-10-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper_trading", "0002_alter_apiusagetracker_requests_limit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiusagetracker",
            name="requests_limit",
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
