# Generated by Django 5.2.6 on 2025-10-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper_trading", "0003_alter_apiusagetracker_requests_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="papertrade",
            name="exit_reason",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
