# Generated by Django 5.2.6 on 2025-10-09 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper_trading", "0005_papertrade_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_addresses",
                    models.JSONField(
                        default=list, help_text="List of email addresses to notify"
                    ),
                ),
                (
                    "phone_numbers",
                    models.JSONField(
                        default=list,
                        help_text="List of phone numbers for SMS (E.164 format: +1234567890)",
                    ),
                ),
                (
                    "signal_filter",
                    models.CharField(
                        choices=[
                            ("all", "All Signals"),
                            ("bullish", "Bullish Only"),
                            ("bearish", "Bearish Only"),
                        ],
                        default="all",
                        help_text="Filter signals by direction",
                        max_length=10,
                    ),
                ),
                (
                    "pair_filter",
                    models.JSONField(
                        default=list,
                        help_text="List of pairs to monitor (empty = all pairs)",
                    ),
                ),
                ("notify_new_signal", models.BooleanField(default=True)),
                ("notify_trade_opened", models.BooleanField(default=True)),
                ("notify_trade_closed", models.BooleanField(default=True)),
                ("notify_tp_hit", models.BooleanField(default=True)),
                ("notify_sl_hit", models.BooleanField(default=True)),
                ("notify_system_status", models.BooleanField(default=True)),
                ("notify_candle_prediction", models.BooleanField(default=False)),
                (
                    "notify_high_confidence",
                    models.BooleanField(
                        default=True,
                        help_text="Notify for signals with 80%+ confidence",
                    ),
                ),
                ("enable_email", models.BooleanField(default=True)),
                ("enable_sms", models.BooleanField(default=False)),
                ("enable_push", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                (
                    "min_confidence",
                    models.IntegerField(
                        default=75,
                        help_text="Minimum signal confidence to notify (0-100)",
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True,
                        help_text="Start of quiet hours (no notifications)",
                        null=True,
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True, help_text="End of quiet hours", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_prefs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("signal", "New Signal"),
                            ("trade_opened", "Trade Opened"),
                            ("trade_closed", "Trade Closed"),
                            ("tp_hit", "Take Profit Hit"),
                            ("sl_hit", "Stop Loss Hit"),
                            ("system_status", "System Status"),
                            ("candle_prediction", "Candle Prediction"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "recipient",
                    models.CharField(help_text="Email or phone number", max_length=255),
                ),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "metadata",
                    models.JSONField(default=dict, help_text="Signal/trade data"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("retry", "Retrying"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="notificatio_user_id_b7181f_idx",
                    ),
                    models.Index(
                        fields=["status"], name="notificatio_status_2a4540_idx"
                    ),
                ],
            },
        ),
    ]
