name: Deploy to Cloud Run

on:
  push:
    branches: [ main, enhancements_backend ]
    paths:
      - 'forex_signal/**'
      - 'signals/**'
      - 'requirements.txt'
      - 'Dockerfile'
      - 'manage.py'
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ env.GCP_PROJECT_ID }}/forex-trading-api:$GITHUB_SHA .

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy forex-trading-api \
          --image gcr.io/${{ env.GCP_PROJECT_ID }}/forex-trading-api:$GITHUB_SHA \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated \
          --set-env-vars="DJANGO_SETTINGS_MODULE=forex_signal.settings,DEBUG=False" \
          --memory=2Gi \
          --cpu=1 \
          --max-instances=10 \
          --timeout=300 \
          --port=8000

    - name: Test deployment
      run: |
        # Wait a moment for deployment to be ready
        sleep 30
        # Test the API endpoint
        curl -f https://congenial-fortnight-1034520618737.europe-west1.run.app/api/signals/ || exit 1