name: Dry Run CI

on:
  push:
    paths:
      - 'scripts/**'
      - 'tests/**'
      - 'data/tests/**'
  pull_request:
    paths:
      - 'scripts/**'
      - 'tests/**'
      - 'data/tests/**'

jobs:
  test-and-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install TA-Lib system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget build-essential
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib/
          ./configure --prefix=/usr
          make
          sudo make install
          sudo ldconfig

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-tests.txt
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          pytest -q --tb=short

      - name: Run automated dry-run
        run: |
          python scripts/automated_training.py --dry-run --dry-iterations 3 --na-threshold 0.5 --pairs EURUSD XAUUSD
