name: Update Price Data at US Close

on:
  schedule:
    # Run at 9 PM UTC (4 PM ET) Monday-Friday (US market close)
    - cron: '0 21 * * 1-5'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-price-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas schedule
      
      - name: Update price data
        run: |
          python scripts/data_update_scheduler.py --once
        env:
          PYTHONUNBUFFERED: 1
      
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add data/
          git diff --quiet && git diff --staged --quiet || (
            git commit -m "chore: Update price data - US market close $(date -u +%Y-%m-%d)"
            git push
          )
        continue-on-error: true
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: updated-price-data
          path: data/*_H1.csv
          retention-days: 7
